version: '3.1'

services:

  mongo:
    image: mongo:4.2
    container_name: mongo
    restart: always
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - bdd:/data/db
    networks:
      vagrant:
        ipv4_address: ${BDD_IP}

  back:
    image: benjaminosty/back
    container_name: back
    restart: always
    ports:
    - 3000:3000
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://root:password@mongo:27017
      SECRET: S3CR3T
    networks:
      vagrant:
        ipv4_address: ${BACK_IP}

  front:
    image: benjaminosty/front
    container_name: front
    restart: always
    ports:
    - 80:80
    networks:
      vagrant:
        ipv4_address: ${FRONT_IP}

volumes:
  bdd:

networks:
  vagrant:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}
