Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.network "public_network", :bridge => "ens33", ip: "192.168.8.236"
  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provision "file", source: "nginx.conf", destination: "/home/vagrant/nginx/nginx.conf"

  config.vm.provision :shell, :path => "secrets.sh"
  config.vm.provision :shell, :path => "bootstrap.sh"
#  config.vm.provision :shell, :path => "mongo.sh"
end
